### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by alwnraj**
fixed some spelling mistakes.

### CODE REVIEW

**Comment by ImSammy6** [comment]
dang if only Sabrina had some way to practice spelling

**Comment by kaelonR** [comment]
> i

We should make an app for that!

**Comment by kaelonR** [comment]
> dang if only Sabrina had some way to practice spelling

We should make an app to help her practice!

**Comment by pauliesnug** [comment]
> fixed some spelling mistakes.

the whole point is that the spelling mistakes were intentional

**Comment by joseph-468** [comment]
These are intentional. They are all in spans with the class "error".

**Pull request closed without merging**
